# Base configs
baseurl: "https://katj.kosenko.eu"
portfolio_location: "images/portfolio"

# UI configs
title: "Katja Kosenko"
subtitle: "Grafikdesignerin"

collections:
  portfolio:
    output: true
    permalink: /:name



